version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - sudo pip install boto3
      - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
      - unzip terraform_0.10.4_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_0.10.4_linux_amd64.zip
  build:
    commands:
      - cd terraform-code
	  - terraform init
	  - terraform plan
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
