version: 0.2

#env:
#  variables:
#    key: "value"
#    key: "value"

phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
      - unzip terraform_0.10.4_linux_amd64.zip
      - sudo mv terraform /bin
      - rm terraform_0.10.4_linux_amd64.zip
  build:
    commands:
      - export $AWS_ACCESS_KEY_ID
      - export $AWS_SECRET_ACCESS_KEY
      - cd terraformsample
      - terraform init
      - terraform plan
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
